echo -e "input_0::\n"
./a.out input_pa1/input_0.dat out_0.dat
./checker/checker_linux input_pa1/input_0.dat out_0.dat
echo -e "input_1::\n"
./a.out input_pa1/input_1.dat out_1.dat
./checker/checker_linux input_pa1/input_1.dat out_1.dat
echo -e "input_2::\n"
./a.out input_pa1/input_2.dat out_2.dat
./checker/checker_linux input_pa1/input_2.dat out_2.dat
echo -e "input_3::\n"
./a.out input_pa1/input_3.dat out_3.dat
./checker/checker_linux input_pa1/input_3.dat out_3.dat
echo -e "input_4::\n"
./a.out input_pa1/input_4.dat out_4.dat
./checker/checker_linux input_pa1/input_4.dat out_4.dat
echo -e "input_5::\n"
./a.out input_pa1/input_5.dat out_5.dat
./checker/checker_linux input_pa1/input_5.dat out_5.dat
echo -e "input_6::\n"
./a.out input_pa1/input_6.dat out_6.dat
./checker/checker_linux input_pa1/input_6.dat out_6.dat
